//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EspacioDelimitado
    {
        public int IdEspacioDelimitado { get; set; }
        public string Coord1 { get; set; }
        public string Coord2 { get; set; }
        public string Coord3 { get; set; }
        public string Coord4 { get; set; }
        public Nullable<bool> Habilitado { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> Eliminado { get; set; }
        public Nullable<int> IdCalibracion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        public virtual Calibracion Calibracion { get; set; }
    }
}
